services:
    moviewatchlist-api:
      build:      
        context: .
        dockerfile: ./Dockerfile
      depends_on: [ moviewatchlist-redis, moviewatchlist-db ]    
      ports:
        - "8080:80"
      environment:
        ConnectionStrings:Postgres: Server=host.docker.internal;Port=5432;Database=moviewatchlist;User ID=postgres;Password=postgres;
        ConnectionStrings:Redis: localhost:6379
        ASPNETCORE_ENVIRONMENT: Development
    moviewatchlist-redis:
      image: redis:7.2.3-alpine
      restart: always
      ports:
        - '6379:6379'
    moviewatchlist-db:
      image: postgres:16.0-bullseye
      restart: always
      ports:
        - '5432:5432'
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: moviewatchlist
      volumes:
        - ./src/MovieWatchlist.Infrastructure/init.sql:/docker-entrypoint-initdb.d/init.sql
        - moviewatchlist-data:/var/lib/postgresql/data
volumes:
  moviewatchlist-data:
    driver: local