services:
    moviewatchlist-api:
      build:      
        context: .
        dockerfile: ./Dockerfile
      depends_on: [ moviewatchlist-db ]    
      ports:
        - "8080:80"
      environment:
        ConnectionStrings:MovieWatchlist: Server=host.docker.internal;Port=5432;Database=moviewatchlist;User ID=postgres;Password=postgres;
        ASPNETCORE_ENVIRONMENT: Development
    moviewatchlist-db:
      image: postgres:14.5-bullseye
      restart: always
      ports:
        - '5432:5432'
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: moviewatchlist
      volumes:
        - moviewatchlist-db:/var/lib/postgresql/data
volumes:
  moviewatchlist-db:
    driver: local