services:
    moviewatchlist-api:
      build:      
        context: .
        dockerfile: ./Dockerfile
      depends_on: [ moviewatchlist-db ]    
      ports:
        - "8080:80"
    moviewatchlist-db:
      image: postgres:14.5-bullseye
      restart: always
      ports:
        - '5432:5432'
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: moviewatchlist
      volumes:
        - moviewatchlist-db:/var/lib/postgresql/data
        - ./moviewatchlist-db/top250Movies.csv:/docker-entrypoint-initdb.d/top250Movies.csv
        - ./moviewatchlist-db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  moviewatchlist-db:
    driver: local