// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieWatchlist.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MovieWatchlist.Infrastructure.Migrations
{
    [DbContext(typeof(MovieWatchlistContext))]
    [Migration("20230918221513_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MovieWatchlist.Application.Models.Movie", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int?>("Ranking")
                        .HasColumnType("integer");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric(2,1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Movies", "Movies");

                    b.HasData(
                        new
                        {
                            Id = "0111161",
                            Ranking = 1,
                            Rating = 9.3m,
                            Title = "The Shawshank Redemption (1994)"
                        },
                        new
                        {
                            Id = "0068646",
                            Ranking = 2,
                            Rating = 9.2m,
                            Title = "The Godfather (1972)"
                        },
                        new
                        {
                            Id = "0468569",
                            Ranking = 3,
                            Rating = 9.0m,
                            Title = "The Dark Knight (2008)"
                        },
                        new
                        {
                            Id = "0071562",
                            Ranking = 4,
                            Rating = 9.0m,
                            Title = "The Godfather: Part II (1974)"
                        },
                        new
                        {
                            Id = "0050083",
                            Ranking = 5,
                            Rating = 9.0m,
                            Title = "12 Angry Men (1957)"
                        },
                        new
                        {
                            Id = "0108052",
                            Ranking = 6,
                            Rating = 9.0m,
                            Title = "Schindler's List (1993)"
                        },
                        new
                        {
                            Id = "0167260",
                            Ranking = 7,
                            Rating = 9.0m,
                            Title = "The Lord of the Rings: The Return of the King (2003)"
                        },
                        new
                        {
                            Id = "0110912",
                            Ranking = 8,
                            Rating = 8.9m,
                            Title = "Pulp Fiction (1994)"
                        },
                        new
                        {
                            Id = "0120737",
                            Ranking = 9,
                            Rating = 8.8m,
                            Title = "The Lord of the Rings: The Fellowship of the Ring (2001)"
                        },
                        new
                        {
                            Id = "0060196",
                            Ranking = 10,
                            Rating = 8.8m,
                            Title = "Il buono, il brutto, il cattivo (1966)"
                        },
                        new
                        {
                            Id = "0109830",
                            Ranking = 11,
                            Rating = 8.8m,
                            Title = "Forrest Gump (1994)"
                        },
                        new
                        {
                            Id = "0137523",
                            Ranking = 12,
                            Rating = 8.8m,
                            Title = "Fight Club (1999)"
                        },
                        new
                        {
                            Id = "0167261",
                            Ranking = 13,
                            Rating = 8.8m,
                            Title = "The Lord of the Rings: The Two Towers (2002)"
                        },
                        new
                        {
                            Id = "1375666",
                            Ranking = 14,
                            Rating = 8.8m,
                            Title = "Inception (2010)"
                        },
                        new
                        {
                            Id = "0080684",
                            Ranking = 15,
                            Rating = 8.7m,
                            Title = "The Empire Strikes Back (1980)"
                        },
                        new
                        {
                            Id = "0133093",
                            Ranking = 16,
                            Rating = 8.7m,
                            Title = "The Matrix (1999)"
                        },
                        new
                        {
                            Id = "0099685",
                            Ranking = 17,
                            Rating = 8.7m,
                            Title = "Goodfellas (1990)"
                        },
                        new
                        {
                            Id = "0073486",
                            Ranking = 18,
                            Rating = 8.7m,
                            Title = "One Flew Over the Cuckoo's Nest (1975)"
                        },
                        new
                        {
                            Id = "9362722",
                            Ranking = 19,
                            Rating = 8.7m,
                            Title = "Spider-Man: Across the Spider-Verse (2023)"
                        },
                        new
                        {
                            Id = "0114369",
                            Ranking = 20,
                            Rating = 8.6m,
                            Title = "Se7en (1995)"
                        },
                        new
                        {
                            Id = "0038650",
                            Ranking = 21,
                            Rating = 8.6m,
                            Title = "It's a Wonderful Life (1946)"
                        },
                        new
                        {
                            Id = "0047478",
                            Ranking = 22,
                            Rating = 8.6m,
                            Title = "Shichinin no samurai (1954)"
                        },
                        new
                        {
                            Id = "0102926",
                            Ranking = 23,
                            Rating = 8.6m,
                            Title = "The Silence of the Lambs (1991)"
                        },
                        new
                        {
                            Id = "0816692",
                            Ranking = 24,
                            Rating = 8.7m,
                            Title = "Interstellar (2014)"
                        },
                        new
                        {
                            Id = "0120815",
                            Ranking = 25,
                            Rating = 8.6m,
                            Title = "Saving Private Ryan (1998)"
                        },
                        new
                        {
                            Id = "0317248",
                            Ranking = 26,
                            Rating = 8.6m,
                            Title = "Cidade de Deus (2002)"
                        },
                        new
                        {
                            Id = "0118799",
                            Ranking = 27,
                            Rating = 8.6m,
                            Title = "La Vita è bella (1997)"
                        },
                        new
                        {
                            Id = "0120689",
                            Ranking = 28,
                            Rating = 8.6m,
                            Title = "The Green Mile (1999)"
                        },
                        new
                        {
                            Id = "0076759",
                            Ranking = 29,
                            Rating = 8.6m,
                            Title = "Star Wars (1977)"
                        },
                        new
                        {
                            Id = "0103064",
                            Ranking = 30,
                            Rating = 8.6m,
                            Title = "Terminator 2: Judgment Day (1991)"
                        },
                        new
                        {
                            Id = "0088763",
                            Ranking = 31,
                            Rating = 8.5m,
                            Title = "Back to the Future (1985)"
                        },
                        new
                        {
                            Id = "0245429",
                            Ranking = 32,
                            Rating = 8.6m,
                            Title = "Sen to Chihiro no kamikakushi (2001)"
                        },
                        new
                        {
                            Id = "0253474",
                            Ranking = 33,
                            Rating = 8.5m,
                            Title = "The Pianist (2002)"
                        },
                        new
                        {
                            Id = "0054215",
                            Ranking = 34,
                            Rating = 8.5m,
                            Title = "Psycho (1960)"
                        },
                        new
                        {
                            Id = "6751668",
                            Ranking = 35,
                            Rating = 8.5m,
                            Title = "Gisaengchung (2019)"
                        },
                        new
                        {
                            Id = "0172495",
                            Ranking = 36,
                            Rating = 8.5m,
                            Title = "Gladiator (2000)"
                        },
                        new
                        {
                            Id = "0110357",
                            Ranking = 37,
                            Rating = 8.5m,
                            Title = "The Lion King (1994)"
                        },
                        new
                        {
                            Id = "0110413",
                            Ranking = 38,
                            Rating = 8.5m,
                            Title = "Léon (1994)"
                        },
                        new
                        {
                            Id = "0120586",
                            Ranking = 39,
                            Rating = 8.5m,
                            Title = "American History X (1998)"
                        },
                        new
                        {
                            Id = "0407887",
                            Ranking = 40,
                            Rating = 8.5m,
                            Title = "The Departed (2006)"
                        },
                        new
                        {
                            Id = "2582802",
                            Ranking = 41,
                            Rating = 8.5m,
                            Title = "Whiplash (2014)"
                        },
                        new
                        {
                            Id = "0482571",
                            Ranking = 42,
                            Rating = 8.5m,
                            Title = "The Prestige (2006)"
                        },
                        new
                        {
                            Id = "15398776",
                            Ranking = 43,
                            Rating = 8.6m,
                            Title = "Oppenheimer (2023)"
                        },
                        new
                        {
                            Id = "0114814",
                            Ranking = 44,
                            Rating = 8.5m,
                            Title = "The Usual Suspects (1995)"
                        },
                        new
                        {
                            Id = "0095327",
                            Ranking = 45,
                            Rating = 8.5m,
                            Title = "Hotaru no haka (1988)"
                        },
                        new
                        {
                            Id = "0056058",
                            Ranking = 46,
                            Rating = 8.6m,
                            Title = "Seppuku (1962)"
                        },
                        new
                        {
                            Id = "0034583",
                            Ranking = 47,
                            Rating = 8.5m,
                            Title = "Casablanca (1942)"
                        },
                        new
                        {
                            Id = "1675434",
                            Ranking = 48,
                            Rating = 8.5m,
                            Title = "Intouchables (2011)"
                        },
                        new
                        {
                            Id = "0027977",
                            Ranking = 49,
                            Rating = 8.5m,
                            Title = "Modern Times (1936)"
                        },
                        new
                        {
                            Id = "0095765",
                            Ranking = 50,
                            Rating = 8.5m,
                            Title = "Nuovo Cinema Paradiso (1988)"
                        },
                        new
                        {
                            Id = "0064116",
                            Ranking = 51,
                            Rating = 8.5m,
                            Title = "C'era una volta il West (1968)"
                        },
                        new
                        {
                            Id = "0047396",
                            Ranking = 52,
                            Rating = 8.5m,
                            Title = "Rear Window (1954)"
                        },
                        new
                        {
                            Id = "0078748",
                            Ranking = 53,
                            Rating = 8.5m,
                            Title = "Alien (1979)"
                        },
                        new
                        {
                            Id = "0021749",
                            Ranking = 54,
                            Rating = 8.5m,
                            Title = "City Lights (1931)"
                        },
                        new
                        {
                            Id = "0078788",
                            Ranking = 55,
                            Rating = 8.4m,
                            Title = "Apocalypse Now (1979)"
                        },
                        new
                        {
                            Id = "0209144",
                            Ranking = 56,
                            Rating = 8.4m,
                            Title = "Memento (2000)"
                        },
                        new
                        {
                            Id = "1853728",
                            Ranking = 57,
                            Rating = 8.5m,
                            Title = "Django Unchained (2012)"
                        },
                        new
                        {
                            Id = "0082971",
                            Ranking = 58,
                            Rating = 8.4m,
                            Title = "Raiders of the Lost Ark (1981)"
                        },
                        new
                        {
                            Id = "0910970",
                            Ranking = 59,
                            Rating = 8.4m,
                            Title = "WALL·E (2008)"
                        },
                        new
                        {
                            Id = "0405094",
                            Ranking = 60,
                            Rating = 8.4m,
                            Title = "Das Leben der Anderen (2006)"
                        },
                        new
                        {
                            Id = "0043014",
                            Ranking = 61,
                            Rating = 8.4m,
                            Title = "Sunset Blvd. (1950)"
                        },
                        new
                        {
                            Id = "0050825",
                            Ranking = 62,
                            Rating = 8.4m,
                            Title = "Paths of Glory (1957)"
                        },
                        new
                        {
                            Id = "4154756",
                            Ranking = 63,
                            Rating = 8.4m,
                            Title = "Avengers: Infinity War (2018)"
                        },
                        new
                        {
                            Id = "0081505",
                            Ranking = 64,
                            Rating = 8.4m,
                            Title = "The Shining (1980)"
                        },
                        new
                        {
                            Id = "0032553",
                            Ranking = 65,
                            Rating = 8.4m,
                            Title = "The Great Dictator (1940)"
                        },
                        new
                        {
                            Id = "0051201",
                            Ranking = 66,
                            Rating = 8.4m,
                            Title = "Witness for the Prosecution (1957)"
                        },
                        new
                        {
                            Id = "4633694",
                            Ranking = 67,
                            Rating = 8.4m,
                            Title = "Spider-Man: Into the Spider-Verse (2018)"
                        },
                        new
                        {
                            Id = "0090605",
                            Ranking = 68,
                            Rating = 8.4m,
                            Title = "Aliens (1986)"
                        },
                        new
                        {
                            Id = "1345836",
                            Ranking = 69,
                            Rating = 8.4m,
                            Title = "The Dark Knight Rises (2012)"
                        },
                        new
                        {
                            Id = "0361748",
                            Ranking = 70,
                            Rating = 8.3m,
                            Title = "Inglourious Basterds (2009)"
                        },
                        new
                        {
                            Id = "0169547",
                            Ranking = 71,
                            Rating = 8.3m,
                            Title = "American Beauty (1999)"
                        },
                        new
                        {
                            Id = "0057012",
                            Ranking = 72,
                            Rating = 8.4m,
                            Title = "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964)"
                        },
                        new
                        {
                            Id = "0364569",
                            Ranking = 73,
                            Rating = 8.4m,
                            Title = "Oldeuboi (2003)"
                        },
                        new
                        {
                            Id = "2380307",
                            Ranking = 74,
                            Rating = 8.4m,
                            Title = "Coco (2017)"
                        },
                        new
                        {
                            Id = "0086879",
                            Ranking = 75,
                            Rating = 8.4m,
                            Title = "Amadeus (1984)"
                        },
                        new
                        {
                            Id = "0114709",
                            Ranking = 76,
                            Rating = 8.3m,
                            Title = "Toy Story (1995)"
                        },
                        new
                        {
                            Id = "0082096",
                            Ranking = 77,
                            Rating = 8.4m,
                            Title = "Das Boot (1981)"
                        },
                        new
                        {
                            Id = "0112573",
                            Ranking = 78,
                            Rating = 8.3m,
                            Title = "Braveheart (1995)"
                        },
                        new
                        {
                            Id = "4154796",
                            Ranking = 79,
                            Rating = 8.4m,
                            Title = "Avengers: Endgame (2019)"
                        },
                        new
                        {
                            Id = "7286456",
                            Ranking = 80,
                            Rating = 8.4m,
                            Title = "Joker (2019)"
                        },
                        new
                        {
                            Id = "0119698",
                            Ranking = 81,
                            Rating = 8.3m,
                            Title = "Mononoke-hime (1997)"
                        },
                        new
                        {
                            Id = "0119217",
                            Ranking = 82,
                            Rating = 8.3m,
                            Title = "Good Will Hunting (1997)"
                        },
                        new
                        {
                            Id = "0087843",
                            Ranking = 83,
                            Rating = 8.3m,
                            Title = "Once Upon a Time in America (1984)"
                        },
                        new
                        {
                            Id = "5311514",
                            Ranking = 84,
                            Rating = 8.4m,
                            Title = "Kimi no na wa. (2016)"
                        },
                        new
                        {
                            Id = "1187043",
                            Ranking = 85,
                            Rating = 8.4m,
                            Title = "3 Idiots (2009)"
                        },
                        new
                        {
                            Id = "0057565",
                            Ranking = 86,
                            Rating = 8.4m,
                            Title = "Tengoku to jigoku (1963)"
                        },
                        new
                        {
                            Id = "0045152",
                            Ranking = 87,
                            Rating = 8.3m,
                            Title = "Singin' in the Rain (1952)"
                        },
                        new
                        {
                            Id = "0180093",
                            Ranking = 88,
                            Rating = 8.3m,
                            Title = "Requiem for a Dream (2000)"
                        },
                        new
                        {
                            Id = "8267604",
                            Ranking = 89,
                            Rating = 8.4m,
                            Title = "Capharnaüm (2018)"
                        },
                        new
                        {
                            Id = "0435761",
                            Ranking = 90,
                            Rating = 8.3m,
                            Title = "Toy Story 3 (2010)"
                        },
                        new
                        {
                            Id = "0091251",
                            Ranking = 91,
                            Rating = 8.4m,
                            Title = "Idi i smotri (1985)"
                        },
                        new
                        {
                            Id = "0086190",
                            Ranking = 92,
                            Rating = 8.3m,
                            Title = "Star Wars: Episode VI - Return of the Jedi (1983)"
                        },
                        new
                        {
                            Id = "0338013",
                            Ranking = 93,
                            Rating = 8.3m,
                            Title = "Eternal Sunshine of the Spotless Mind (2004)"
                        },
                        new
                        {
                            Id = "0062622",
                            Ranking = 94,
                            Rating = 8.3m,
                            Title = "2001: A Space Odyssey (1968)"
                        },
                        new
                        {
                            Id = "2106476",
                            Ranking = 95,
                            Rating = 8.3m,
                            Title = "Jagten (2012)"
                        },
                        new
                        {
                            Id = "0105236",
                            Ranking = 96,
                            Rating = 8.3m,
                            Title = "Reservoir Dogs (1992)"
                        },
                        new
                        {
                            Id = "0044741",
                            Ranking = 97,
                            Rating = 8.3m,
                            Title = "Ikiru (1952)"
                        },
                        new
                        {
                            Id = "0056172",
                            Ranking = 98,
                            Rating = 8.3m,
                            Title = "Lawrence of Arabia (1962)"
                        },
                        new
                        {
                            Id = "0033467",
                            Ranking = 99,
                            Rating = 8.3m,
                            Title = "Citizen Kane (1941)"
                        },
                        new
                        {
                            Id = "0022100",
                            Ranking = 100,
                            Rating = 8.3m,
                            Title = "M (1931)"
                        },
                        new
                        {
                            Id = "0053604",
                            Ranking = 101,
                            Rating = 8.3m,
                            Title = "The Apartment (1960)"
                        },
                        new
                        {
                            Id = "0053125",
                            Ranking = 102,
                            Rating = 8.3m,
                            Title = "North by Northwest (1959)"
                        },
                        new
                        {
                            Id = "0052357",
                            Ranking = 103,
                            Rating = 8.3m,
                            Title = "Vertigo (1958)"
                        },
                        new
                        {
                            Id = "0036775",
                            Ranking = 104,
                            Rating = 8.3m,
                            Title = "Double Indemnity (1944)"
                        },
                        new
                        {
                            Id = "0211915",
                            Ranking = 105,
                            Rating = 8.3m,
                            Title = "Le Fabuleux destin d'Amélie Poulain (2001)"
                        },
                        new
                        {
                            Id = "0086250",
                            Ranking = 106,
                            Rating = 8.3m,
                            Title = "Scarface (1983)"
                        },
                        new
                        {
                            Id = "0093058",
                            Ranking = 107,
                            Rating = 8.3m,
                            Title = "Full Metal Jacket (1987)"
                        },
                        new
                        {
                            Id = "0066921",
                            Ranking = 108,
                            Rating = 8.3m,
                            Title = "A Clockwork Orange (1971)"
                        },
                        new
                        {
                            Id = "1255953",
                            Ranking = 109,
                            Rating = 8.3m,
                            Title = "Incendies (2010)"
                        },
                        new
                        {
                            Id = "0113277",
                            Ranking = 110,
                            Rating = 8.3m,
                            Title = "Heat (1995)"
                        },
                        new
                        {
                            Id = "8503618",
                            Ranking = 111,
                            Rating = 8.3m,
                            Title = "Hamilton (2020)"
                        },
                        new
                        {
                            Id = "1049413",
                            Ranking = 112,
                            Rating = 8.3m,
                            Title = "Up (2009)"
                        },
                        new
                        {
                            Id = "0056592",
                            Ranking = 113,
                            Rating = 8.3m,
                            Title = "To Kill a Mockingbird (1962)"
                        },
                        new
                        {
                            Id = "0070735",
                            Ranking = 114,
                            Rating = 8.3m,
                            Title = "The Sting (1973)"
                        },
                        new
                        {
                            Id = "1832382",
                            Ranking = 115,
                            Rating = 8.3m,
                            Title = "Jodaeiye Nader az Simin (2011)"
                        },
                        new
                        {
                            Id = "0097576",
                            Ranking = 116,
                            Rating = 8.2m,
                            Title = "Indiana Jones and the Last Crusade (1989)"
                        },
                        new
                        {
                            Id = "0017136",
                            Ranking = 117,
                            Rating = 8.3m,
                            Title = "Metropolis (1927)"
                        },
                        new
                        {
                            Id = "0095016",
                            Ranking = 118,
                            Rating = 8.2m,
                            Title = "Die Hard (1988)"
                        },
                        new
                        {
                            Id = "0119488",
                            Ranking = 119,
                            Rating = 8.2m,
                            Title = "L.A. Confidential (1997)"
                        },
                        new
                        {
                            Id = "0040522",
                            Ranking = 120,
                            Rating = 8.3m,
                            Title = "Ladri di biciclette (1948)"
                        },
                        new
                        {
                            Id = "0208092",
                            Ranking = 121,
                            Rating = 8.2m,
                            Title = "Snatch. (2000)"
                        },
                        new
                        {
                            Id = "0986264",
                            Ranking = 122,
                            Rating = 8.3m,
                            Title = "Taare Zameen Par (2007)"
                        },
                        new
                        {
                            Id = "0075314",
                            Ranking = 123,
                            Rating = 8.2m,
                            Title = "Taxi Driver (1976)"
                        },
                        new
                        {
                            Id = "8579674",
                            Ranking = 124,
                            Rating = 8.2m,
                            Title = "1917 (2019)"
                        },
                        new
                        {
                            Id = "0363163",
                            Ranking = 125,
                            Rating = 8.2m,
                            Title = "Der Untergang (2004)"
                        },
                        new
                        {
                            Id = "5074352",
                            Ranking = 126,
                            Rating = 8.3m,
                            Title = "Dangal (2016)"
                        },
                        new
                        {
                            Id = "1745960",
                            Ranking = 127,
                            Rating = 8.3m,
                            Title = "Top Gun: Maverick (2022)"
                        },
                        new
                        {
                            Id = "0059578",
                            Ranking = 128,
                            Rating = 8.2m,
                            Title = "Per qualche dollaro in più (1965)"
                        },
                        new
                        {
                            Id = "0372784",
                            Ranking = 129,
                            Rating = 8.2m,
                            Title = "Batman Begins (2005)"
                        },
                        new
                        {
                            Id = "0053291",
                            Ranking = 130,
                            Rating = 8.2m,
                            Title = "Some Like It Hot (1959)"
                        },
                        new
                        {
                            Id = "0012349",
                            Ranking = 131,
                            Rating = 8.2m,
                            Title = "The Kid (1921)"
                        },
                        new
                        {
                            Id = "0993846",
                            Ranking = 132,
                            Rating = 8.2m,
                            Title = "The Wolf of Wall Street (2013)"
                        },
                        new
                        {
                            Id = "10272386",
                            Ranking = 133,
                            Rating = 8.2m,
                            Title = "The Father (2020)"
                        },
                        new
                        {
                            Id = "6966692",
                            Ranking = 134,
                            Rating = 8.2m,
                            Title = "Green Book (2018)"
                        },
                        new
                        {
                            Id = "0042192",
                            Ranking = 135,
                            Rating = 8.2m,
                            Title = "All About Eve (1950)"
                        },
                        new
                        {
                            Id = "0055031",
                            Ranking = 136,
                            Rating = 8.3m,
                            Title = "Judgment at Nuremberg (1961)"
                        },
                        new
                        {
                            Id = "0120382",
                            Ranking = 137,
                            Rating = 8.2m,
                            Title = "The Truman Show (1998)"
                        },
                        new
                        {
                            Id = "0469494",
                            Ranking = 138,
                            Rating = 8.2m,
                            Title = "There Will Be Blood (2007)"
                        },
                        new
                        {
                            Id = "0089881",
                            Ranking = 139,
                            Rating = 8.2m,
                            Title = "Ran (1985)"
                        },
                        new
                        {
                            Id = "0112641",
                            Ranking = 140,
                            Rating = 8.2m,
                            Title = "Casino (1995)"
                        },
                        new
                        {
                            Id = "1130884",
                            Ranking = 141,
                            Rating = 8.2m,
                            Title = "Shutter Island (2010)"
                        },
                        new
                        {
                            Id = "0457430",
                            Ranking = 142,
                            Rating = 8.2m,
                            Title = "El Laberinto del fauno (2006)"
                        },
                        new
                        {
                            Id = "0167404",
                            Ranking = 143,
                            Rating = 8.2m,
                            Title = "The Sixth Sense (1999)"
                        },
                        new
                        {
                            Id = "0105695",
                            Ranking = 144,
                            Rating = 8.2m,
                            Title = "Unforgiven (1992)"
                        },
                        new
                        {
                            Id = "0107290",
                            Ranking = 145,
                            Rating = 8.2m,
                            Title = "Jurassic Park (1993)"
                        },
                        new
                        {
                            Id = "0268978",
                            Ranking = 146,
                            Rating = 8.2m,
                            Title = "A Beautiful Mind (2001)"
                        },
                        new
                        {
                            Id = "0040897",
                            Ranking = 147,
                            Rating = 8.2m,
                            Title = "The Treasure of the Sierra Madre (1948)"
                        },
                        new
                        {
                            Id = "0055630",
                            Ranking = 148,
                            Rating = 8.2m,
                            Title = "Yôjinbô (1961)"
                        },
                        new
                        {
                            Id = "0477348",
                            Ranking = 149,
                            Rating = 8.2m,
                            Title = "No Country for Old Men (2007)"
                        },
                        new
                        {
                            Id = "0266697",
                            Ranking = 150,
                            Rating = 8.2m,
                            Title = "Kill Bill: Vol. 1 (2003)"
                        },
                        new
                        {
                            Id = "0071853",
                            Ranking = 151,
                            Rating = 8.2m,
                            Title = "Monty Python and the Holy Grail (1975)"
                        },
                        new
                        {
                            Id = "0057115",
                            Ranking = 152,
                            Rating = 8.2m,
                            Title = "The Great Escape (1963)"
                        },
                        new
                        {
                            Id = "0084787",
                            Ranking = 153,
                            Rating = 8.2m,
                            Title = "The Thing (1982)"
                        },
                        new
                        {
                            Id = "0042876",
                            Ranking = 154,
                            Rating = 8.2m,
                            Title = "Rashômon (1950)"
                        },
                        new
                        {
                            Id = "0266543",
                            Ranking = 155,
                            Rating = 8.2m,
                            Title = "Finding Nemo (2003)"
                        },
                        new
                        {
                            Id = "0080678",
                            Ranking = 156,
                            Rating = 8.2m,
                            Title = "The Elephant Man (1980)"
                        },
                        new
                        {
                            Id = "0071315",
                            Ranking = 157,
                            Rating = 8.2m,
                            Title = "Chinatown (1974)"
                        },
                        new
                        {
                            Id = "0031381",
                            Ranking = 158,
                            Rating = 8.2m,
                            Title = "Gone with the Wind (1939)"
                        },
                        new
                        {
                            Id = "0347149",
                            Ranking = 159,
                            Rating = 8.2m,
                            Title = "Hauru no ugoku shiro (2004)"
                        },
                        new
                        {
                            Id = "0046912",
                            Ranking = 160,
                            Rating = 8.2m,
                            Title = "Dial M for Murder (1954)"
                        },
                        new
                        {
                            Id = "0434409",
                            Ranking = 161,
                            Rating = 8.2m,
                            Title = "V for Vendetta (2005)"
                        },
                        new
                        {
                            Id = "10872600",
                            Ranking = 162,
                            Rating = 8.2m,
                            Title = "Spider-Man: No Way Home (2021)"
                        },
                        new
                        {
                            Id = "0081398",
                            Ranking = 163,
                            Rating = 8.1m,
                            Title = "Raging Bull (1980)"
                        },
                        new
                        {
                            Id = "0120735",
                            Ranking = 164,
                            Rating = 8.1m,
                            Title = "Lock, Stock and Two Smoking Barrels (1998)"
                        },
                        new
                        {
                            Id = "1305806",
                            Ranking = 165,
                            Rating = 8.2m,
                            Title = "El Secreto de sus ojos (2009)"
                        },
                        new
                        {
                            Id = "2096673",
                            Ranking = 166,
                            Rating = 8.1m,
                            Title = "Inside Out (2015)"
                        },
                        new
                        {
                            Id = "1392214",
                            Ranking = 167,
                            Rating = 8.1m,
                            Title = "Prisoners (2013)"
                        },
                        new
                        {
                            Id = "5027774",
                            Ranking = 168,
                            Rating = 8.1m,
                            Title = "Three Billboards Outside Ebbing, Missouri (2017)"
                        },
                        new
                        {
                            Id = "0050212",
                            Ranking = 169,
                            Rating = 8.1m,
                            Title = "The Bridge on the River Kwai (1957)"
                        },
                        new
                        {
                            Id = "0117951",
                            Ranking = 170,
                            Rating = 8.1m,
                            Title = "Trainspotting (1996)"
                        },
                        new
                        {
                            Id = "0116282",
                            Ranking = 171,
                            Rating = 8.1m,
                            Title = "Fargo (1996)"
                        },
                        new
                        {
                            Id = "1291584",
                            Ranking = 172,
                            Rating = 8.1m,
                            Title = "Warrior (2011)"
                        },
                        new
                        {
                            Id = "1205489",
                            Ranking = 173,
                            Rating = 8.1m,
                            Title = "Gran Torino (2008)"
                        },
                        new
                        {
                            Id = "0264464",
                            Ranking = 174,
                            Rating = 8.1m,
                            Title = "Catch Me If You Can (2002)"
                        },
                        new
                        {
                            Id = "0096283",
                            Ranking = 175,
                            Rating = 8.1m,
                            Title = "Tonari no Totoro (1988)"
                        },
                        new
                        {
                            Id = "0405159",
                            Ranking = 176,
                            Rating = 8.1m,
                            Title = "Million Dollar Baby (2004)"
                        },
                        new
                        {
                            Id = "4729430",
                            Ranking = 177,
                            Rating = 8.2m,
                            Title = "Klaus (2019)"
                        },
                        new
                        {
                            Id = "1201607",
                            Ranking = 178,
                            Rating = 8.1m,
                            Title = "Harry Potter and the Deathly Hallows: Part 2 (2011)"
                        },
                        new
                        {
                            Id = "0118849",
                            Ranking = 179,
                            Rating = 8.2m,
                            Title = "Bacheha-Ye aseman (1997)"
                        },
                        new
                        {
                            Id = "0083658",
                            Ranking = 180,
                            Rating = 8.1m,
                            Title = "Blade Runner (1982)"
                        },
                        new
                        {
                            Id = "2024544",
                            Ranking = 181,
                            Rating = 8.1m,
                            Title = "12 Years a Slave (2013)"
                        },
                        new
                        {
                            Id = "0112471",
                            Ranking = 182,
                            Rating = 8.1m,
                            Title = "Before Sunrise (1995)"
                        },
                        new
                        {
                            Id = "0015864",
                            Ranking = 183,
                            Rating = 8.1m,
                            Title = "The Gold Rush (1925)"
                        },
                        new
                        {
                            Id = "2278388",
                            Ranking = 184,
                            Rating = 8.1m,
                            Title = "The Grand Budapest Hotel (2014)"
                        },
                        new
                        {
                            Id = "0052618",
                            Ranking = 185,
                            Rating = 8.1m,
                            Title = "Ben-Hur (1959)"
                        },
                        new
                        {
                            Id = "2267998",
                            Ranking = 186,
                            Rating = 8.1m,
                            Title = "Gone Girl (2014)"
                        },
                        new
                        {
                            Id = "0072684",
                            Ranking = 187,
                            Rating = 8.1m,
                            Title = "Barry Lyndon (1975)"
                        },
                        new
                        {
                            Id = "0047296",
                            Ranking = 188,
                            Rating = 8.1m,
                            Title = "On the Waterfront (1954)"
                        },
                        new
                        {
                            Id = "2119532",
                            Ranking = 189,
                            Rating = 8.1m,
                            Title = "Hacksaw Ridge (2016)"
                        },
                        new
                        {
                            Id = "0107207",
                            Ranking = 190,
                            Rating = 8.1m,
                            Title = "In the Name of the Father (1993)"
                        },
                        new
                        {
                            Id = "0017925",
                            Ranking = 191,
                            Rating = 8.1m,
                            Title = "The General (1926)"
                        },
                        new
                        {
                            Id = "0353969",
                            Ranking = 192,
                            Rating = 8.1m,
                            Title = "Salinui chueok (2003)"
                        },
                        new
                        {
                            Id = "0077416",
                            Ranking = 193,
                            Rating = 8.1m,
                            Title = "The Deer Hunter (1978)"
                        },
                        new
                        {
                            Id = "0050986",
                            Ranking = 194,
                            Rating = 8.1m,
                            Title = "Smultronstället (1957)"
                        },
                        new
                        {
                            Id = "0046268",
                            Ranking = 195,
                            Rating = 8.2m,
                            Title = "Le Salaire de la peur (1953)"
                        },
                        new
                        {
                            Id = "0041959",
                            Ranking = 196,
                            Rating = 8.1m,
                            Title = "The Third Man (1949)"
                        },
                        new
                        {
                            Id = "3011894",
                            Ranking = 197,
                            Rating = 8.1m,
                            Title = "Relatos salvajes (2014)"
                        },
                        new
                        {
                            Id = "0015324",
                            Ranking = 198,
                            Rating = 8.2m,
                            Title = "Sherlock Jr. (1924)"
                        },
                        new
                        {
                            Id = "1392190",
                            Ranking = 199,
                            Rating = 8.1m,
                            Title = "Mad Max: Fury Road (2015)"
                        },
                        new
                        {
                            Id = "0097165",
                            Ranking = 200,
                            Rating = 8.1m,
                            Title = "Dead Poets Society (1989)"
                        },
                        new
                        {
                            Id = "0031679",
                            Ranking = 201,
                            Rating = 8.1m,
                            Title = "Mr. Smith Goes to Washington (1939)"
                        },
                        new
                        {
                            Id = "0198781",
                            Ranking = 202,
                            Rating = 8.1m,
                            Title = "Monsters, Inc. (2001)"
                        },
                        new
                        {
                            Id = "0892769",
                            Ranking = 203,
                            Rating = 8.1m,
                            Title = "How to Train Your Dragon (2010)"
                        },
                        new
                        {
                            Id = "0073195",
                            Ranking = 204,
                            Rating = 8.1m,
                            Title = "Jaws (1975)"
                        },
                        new
                        {
                            Id = "0978762",
                            Ranking = 205,
                            Rating = 8.1m,
                            Title = "Mary and Max (2009)"
                        },
                        new
                        {
                            Id = "0050976",
                            Ranking = 206,
                            Rating = 8.1m,
                            Title = "Sjunde inseglet, Det (1957)"
                        },
                        new
                        {
                            Id = "3170832",
                            Ranking = 207,
                            Rating = 8.1m,
                            Title = "Room (2015)"
                        },
                        new
                        {
                            Id = "1950186",
                            Ranking = 208,
                            Rating = 8.1m,
                            Title = "Ford v Ferrari (2019)"
                        },
                        new
                        {
                            Id = "0118715",
                            Ranking = 209,
                            Rating = 8.1m,
                            Title = "The Big Lebowski (1998)"
                        },
                        new
                        {
                            Id = "0046438",
                            Ranking = 210,
                            Rating = 8.1m,
                            Title = "Tôkyô monogatari (1953)"
                        },
                        new
                        {
                            Id = "0382932",
                            Ranking = 211,
                            Rating = 8.1m,
                            Title = "Ratatouille (2007)"
                        },
                        new
                        {
                            Id = "0075148",
                            Ranking = 212,
                            Rating = 8.1m,
                            Title = "Rocky (1976)"
                        },
                        new
                        {
                            Id = "0395169",
                            Ranking = 213,
                            Rating = 8.1m,
                            Title = "Hotel Rwanda (2004)"
                        },
                        new
                        {
                            Id = "0019254",
                            Ranking = 214,
                            Rating = 8.1m,
                            Title = "La Passion de Jeanne d'Arc (1928)"
                        },
                        new
                        {
                            Id = "3315342",
                            Ranking = 215,
                            Rating = 8.1m,
                            Title = "Logan (2017)"
                        },
                        new
                        {
                            Id = "0091763",
                            Ranking = 216,
                            Rating = 8.1m,
                            Title = "Platoon (1986)"
                        },
                        new
                        {
                            Id = "1895587",
                            Ranking = 217,
                            Rating = 8.1m,
                            Title = "Spotlight (2015)"
                        },
                        new
                        {
                            Id = "0088247",
                            Ranking = 218,
                            Rating = 8.1m,
                            Title = "The Terminator (1984)"
                        },
                        new
                        {
                            Id = "15097216",
                            Ranking = 219,
                            Rating = 8.8m,
                            Title = "Jai Bhim (2021)"
                        },
                        new
                        {
                            Id = "0381681",
                            Ranking = 220,
                            Rating = 8.1m,
                            Title = "Before Sunset (2004)"
                        },
                        new
                        {
                            Id = "1979320",
                            Ranking = 221,
                            Rating = 8.1m,
                            Title = "Rush (2013)"
                        },
                        new
                        {
                            Id = "0074958",
                            Ranking = 222,
                            Rating = 8.1m,
                            Title = "Network (1976)"
                        },
                        new
                        {
                            Id = "0092005",
                            Ranking = 223,
                            Rating = 8.1m,
                            Title = "Stand by Me (1986)"
                        },
                        new
                        {
                            Id = "0036868",
                            Ranking = 224,
                            Rating = 8.1m,
                            Title = "The Best Years of Our Lives (1946)"
                        },
                        new
                        {
                            Id = "0113247",
                            Ranking = 225,
                            Rating = 8.1m,
                            Title = "La Haine (1995)"
                        },
                        new
                        {
                            Id = "0032138",
                            Ranking = 226,
                            Rating = 8.1m,
                            Title = "The Wizard of Oz (1939)"
                        },
                        new
                        {
                            Id = "0758758",
                            Ranking = 227,
                            Rating = 8.1m,
                            Title = "Into the Wild (2007)"
                        },
                        new
                        {
                            Id = "0070047",
                            Ranking = 228,
                            Rating = 8.1m,
                            Title = "The Exorcist (1973)"
                        },
                        new
                        {
                            Id = "0325980",
                            Ranking = 229,
                            Rating = 8.1m,
                            Title = "Pirates of the Caribbean: The Curse of the Black Pearl (2003)"
                        },
                        new
                        {
                            Id = "0317705",
                            Ranking = 230,
                            Rating = 8.0m,
                            Title = "The Incredibles (2004)"
                        },
                        new
                        {
                            Id = "0035446",
                            Ranking = 231,
                            Rating = 8.2m,
                            Title = "To Be or Not to Be (1942)"
                        },
                        new
                        {
                            Id = "1028532",
                            Ranking = 232,
                            Rating = 8.1m,
                            Title = "Hachi: A Dog's Tale (2009)"
                        },
                        new
                        {
                            Id = "0107048",
                            Ranking = 233,
                            Rating = 8.0m,
                            Title = "Groundhog Day (1993)"
                        },
                        new
                        {
                            Id = "0032551",
                            Ranking = 234,
                            Rating = 8.1m,
                            Title = "The Grapes of Wrath (1940)"
                        },
                        new
                        {
                            Id = "4016934",
                            Ranking = 235,
                            Rating = 8.1m,
                            Title = "Ah-ga-ssi (2016)"
                        },
                        new
                        {
                            Id = "0058946",
                            Ranking = 236,
                            Rating = 8.1m,
                            Title = "La Battaglia di Algeri (1966)"
                        },
                        new
                        {
                            Id = "0476735",
                            Ranking = 237,
                            Rating = 8.2m,
                            Title = "Babam Ve Oglum (2005)"
                        },
                        new
                        {
                            Id = "0245712",
                            Ranking = 238,
                            Rating = 8.1m,
                            Title = "Amores perros (2000)"
                        },
                        new
                        {
                            Id = "0032976",
                            Ranking = 239,
                            Rating = 8.1m,
                            Title = "Rebecca (1940)"
                        },
                        new
                        {
                            Id = "0061512",
                            Ranking = 240,
                            Rating = 8.1m,
                            Title = "Cool Hand Luke (1967)"
                        },
                        new
                        {
                            Id = "0059742",
                            Ranking = 241,
                            Rating = 8.1m,
                            Title = "The Sound of Music (1965)"
                        },
                        new
                        {
                            Id = "0048473",
                            Ranking = 242,
                            Rating = 8.2m,
                            Title = "Pather Panchali (1955)"
                        },
                        new
                        {
                            Id = "0025316",
                            Ranking = 243,
                            Rating = 8.1m,
                            Title = "It Happened One Night (1934)"
                        },
                        new
                        {
                            Id = "0129167",
                            Ranking = 244,
                            Rating = 8.1m,
                            Title = "The Iron Giant (1999)"
                        },
                        new
                        {
                            Id = "1454029",
                            Ranking = 245,
                            Rating = 8.1m,
                            Title = "The Help (2011)"
                        },
                        new
                        {
                            Id = "0053198",
                            Ranking = 246,
                            Rating = 8.1m,
                            Title = "Les Quatre cents coups (1959)"
                        },
                        new
                        {
                            Id = "0060827",
                            Ranking = 247,
                            Rating = 8.1m,
                            Title = "Persona (1966)"
                        },
                        new
                        {
                            Id = "0079470",
                            Ranking = 248,
                            Rating = 8.0m,
                            Title = "Life of Brian (1979)"
                        },
                        new
                        {
                            Id = "0103639",
                            Ranking = 249,
                            Rating = 8.0m,
                            Title = "Aladdin (1992)"
                        },
                        new
                        {
                            Id = "0099348",
                            Ranking = 250,
                            Rating = 8.0m,
                            Title = "Dances with Wolves (1990)"
                        });
                });

            modelBuilder.Entity("MovieWatchlist.Application.Models.Watchlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Watchlists", "Watchlists");
                });

            modelBuilder.Entity("MovieWatchlist.Application.Models.WatchlistsMovies", b =>
                {
                    b.Property<string>("MovieId")
                        .HasColumnType("text");

                    b.Property<Guid>("WatchlistId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Watched")
                        .HasColumnType("boolean");

                    b.HasKey("MovieId", "WatchlistId");

                    b.HasIndex("WatchlistId");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("WatchlistId"), new[] { "MovieId" });

                    b.ToTable("WatchlistsMovies", "Watchlists");
                });

            modelBuilder.Entity("MovieWatchlist.Application.Models.WatchlistsMovies", b =>
                {
                    b.HasOne("MovieWatchlist.Application.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieWatchlist.Application.Models.Watchlist", null)
                        .WithMany()
                        .HasForeignKey("WatchlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
